/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.LowStockAlertDto"][];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.LowStockAlertDto"][];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.LowStockAlertDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                        "application/json": unknown;
                        "text/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.LoginRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.LoginRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.LoginResponse"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.LoginResponse"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.LoginResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.RegisterRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.RegisterRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Dashboard.DashboardSummaryDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Dashboard.DashboardSummaryDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Dashboard.DashboardSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Health.HealthStatusDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Health.HealthStatusDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Health.HealthStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/{name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/{name}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    userId?: number;
                    action?: string;
                    entity?: string;
                    dateFrom?: string;
                    dateTo?: string;
                    isSuccess?: boolean;
                    source?: string;
                    severity?: string;
                    q?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Common.PagedResult`1[[Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto, Stock_Warehouse_Tracking_Project_API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Common.PagedResult`1[[Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto, Stock_Warehouse_Tracking_Project_API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Common.PagedResult`1[[Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto, Stock_Warehouse_Tracking_Project_API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.LogMetaDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.LogMetaDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.LogMetaDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    userId?: number;
                    action?: string;
                    entity?: string;
                    dateFrom?: string;
                    dateTo?: string;
                    isSuccess?: boolean;
                    source?: string;
                    severity?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    ProductId?: number;
                    WarehouseId?: number;
                    Type?: components["schemas"]["Stock_Warehouse_Tracking_Project_API.Domain.Enums.MovementType"];
                    DateFrom?: string;
                    DateTo?: string;
                    UserId?: number;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Common.PagedResult`1[[Stock_Warehouse_Tracking_Project_API.Application.DTOs.Movement.MovementDto, Stock_Warehouse_Tracking_Project_API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Common.PagedResult`1[[Stock_Warehouse_Tracking_Project_API.Application.DTOs.Movement.MovementDto, Stock_Warehouse_Tracking_Project_API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Common.PagedResult`1[[Stock_Warehouse_Tracking_Project_API.Application.DTOs.Movement.MovementDto, Stock_Warehouse_Tracking_Project_API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.UpdateNotificationPreferencesRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.UpdateNotificationPreferencesRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.UpdateNotificationPreferencesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpSettingsDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpSettingsDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpSettingsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.UpdateSmtpSettingsRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.UpdateSmtpSettingsRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.UpdateSmtpSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpSettingsDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpSettingsDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpSettingsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/smtp/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestResultDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestResultDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestResultDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestResultDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestResultDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"][];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"][];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.CreateProductRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.CreateProductRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.CreateProductRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.UpdateProductRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.UpdateProductRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.UpdateProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/stock-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.StockSummaryReportDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.StockSummaryReportDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.StockSummaryReportDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/movement-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    granularity?: string;
                    dateFrom?: string;
                    dateTo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.MovementTrendPointDto"][];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.MovementTrendPointDto"][];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.MovementTrendPointDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/warehouse-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.WarehouseComparisonDto"][];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.WarehouseComparisonDto"][];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.WarehouseComparisonDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    format?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.EmailReportRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.EmailReportRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.EmailReportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.EmailReportResultDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.EmailReportResultDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.EmailReportResultDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    matnr?: string;
                    whId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"][];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"][];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{matnr}/{whId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matnr: string;
                    whId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockInRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockInRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockOutRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockOutRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockOutRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockTransferRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockTransferRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockTransferRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{matnr}/{whId}/threshold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matnr: string;
                    whId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.UpdateStockThresholdRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.UpdateStockThresholdRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.UpdateStockThresholdRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/in/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.BulkStockInRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.BulkStockInRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.BulkStockInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.BulkStockInResultDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.BulkStockInResultDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.BulkStockInResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"][];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"][];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.CreateUserRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.CreateUserRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.CreateUserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UpdateUserRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UpdateUserRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.ChangeRoleRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.ChangeRoleRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.ChangeRoleRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.RoleDto"][];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.RoleDto"][];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.RoleDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"][];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"][];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.CreateWarehouseRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.CreateWarehouseRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.CreateWarehouseRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.UpdateWarehouseRequest"];
                    "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.UpdateWarehouseRequest"];
                    "application/*+json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.UpdateWarehouseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                        "application/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                        "text/json": components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Microsoft.AspNetCore.Mvc.ProblemDetails": {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.Common.PagedResult`1[[Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto, Stock_Warehouse_Tracking_Project_API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": {
            items?: components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto"][];
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            readonly totalPages?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.Common.PagedResult`1[[Stock_Warehouse_Tracking_Project_API.Application.DTOs.Movement.MovementDto, Stock_Warehouse_Tracking_Project_API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": {
            items?: components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Movement.MovementDto"][];
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            readonly totalPages?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.BulkStockInRequest": {
            items?: components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockInRequest"][];
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.BulkStockInResultDto": {
            /** Format: int32 */
            successCount?: number;
            /** Format: int32 */
            failureCount?: number;
            errors?: string[];
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.LowStockAlertDto": {
            materialNo?: string;
            productName?: string;
            warehouseId?: string;
            warehouseName?: string;
            /** Format: double */
            quantity?: number;
            /** Format: double */
            minLevel?: number;
            /** Format: double */
            deficit?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Alert.UpdateStockThresholdRequest": {
            /** Format: double */
            minLevel?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.LoginRequest": {
            email?: string;
            password?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.LoginResponse": {
            token?: string;
            userName?: string;
            role?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Auth.RegisterRequest": {
            name?: string;
            email?: string;
            password?: string;
            /** Format: int32 */
            roleId?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Dashboard.DashboardSummaryDto": {
            sapStatus?: string;
            /** Format: int32 */
            productCount?: number;
            /** Format: int32 */
            warehouseCount?: number;
            /** Format: double */
            totalStockQuantity?: number;
            /** Format: int32 */
            emptyStockLines?: number;
            /** Format: int32 */
            sapOnlyProductCount?: number;
            /** Format: int32 */
            lowStockCount?: number;
            recentMovements?: components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Movement.MovementDto"][];
            warehouseStockDistribution?: components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Dashboard.DistributionItemDto"][];
            categoryStockDistribution?: components["schemas"]["Stock_Warehouse_Tracking_Project_API.Application.DTOs.Dashboard.DistributionItemDto"][];
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Dashboard.DistributionItemDto": {
            code?: string;
            name?: string;
            /** Format: double */
            quantity?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Health.HealthStatusDto": {
            api?: string;
            database?: string;
            sap?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.LogMetaDto": {
            actions?: string[];
            entities?: string[];
            sources?: string[];
            severities?: string[];
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Logging.OperationLogDto": {
            /** Format: int64 */
            logId?: number;
            /** Format: int32 */
            userId?: number;
            userName?: string | null;
            /** Format: int32 */
            actorUserId?: number | null;
            actorUserName?: string | null;
            action?: string;
            entity?: string;
            details?: string | null;
            /** Format: date-time */
            timestamp?: string;
            isSuccess?: boolean;
            errorMessage?: string | null;
            source?: string;
            severity?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Movement.MovementDto": {
            /** Format: int32 */
            movementId?: number;
            type?: components["schemas"]["Stock_Warehouse_Tracking_Project_API.Domain.Enums.MovementType"];
            readonly typeName?: string;
            /** Format: double */
            quantity?: number;
            /** Format: date-time */
            date?: string;
            refNo?: string | null;
            productCode?: string;
            sourceWarehouseCode?: string | null;
            destWarehouseCode?: string | null;
            userName?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.CreateProductRequest": {
            code?: string;
            name?: string;
            unit?: string;
            category?: string | null;
            barcode?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.ProductDto": {
            /** Format: int32 */
            productId?: number;
            code?: string;
            name?: string;
            unit?: string;
            category?: string | null;
            barcode?: string | null;
            /** Format: double */
            minStock?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Product.UpdateProductRequest": {
            name?: string;
            unit?: string;
            category?: string | null;
            barcode?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.EmailReportRequest": {
            to?: string | null;
            /** Format: int32 */
            periodDays?: number;
            includeCsv?: boolean;
            provider?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.EmailReportResultDto": {
            sent?: boolean;
            to?: string;
            message?: string;
            provider?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.MovementTrendPointDto": {
            label?: string;
            /** Format: int32 */
            inCount?: number;
            /** Format: int32 */
            outCount?: number;
            /** Format: int32 */
            transferCount?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.StockSummaryReportDto": {
            /** Format: double */
            totalQuantity?: number;
            /** Format: int32 */
            productCount?: number;
            /** Format: int32 */
            warehouseCount?: number;
            /** Format: int32 */
            lowStockCount?: number;
            /** Format: int32 */
            emptyStockLines?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Report.WarehouseComparisonDto": {
            warehouseCode?: string;
            warehouseName?: string;
            /** Format: double */
            totalQuantity?: number;
            /** Format: int32 */
            lineCount?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockDto": {
            materialNo?: string;
            warehouseId?: string;
            /** Format: double */
            quantity?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockInRequest": {
            materialNo?: string;
            warehouseId?: string;
            /** Format: double */
            quantity?: number;
            refNo?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockOutRequest": {
            materialNo?: string;
            warehouseId?: string;
            /** Format: double */
            quantity?: number;
            refNo?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Stock.StockTransferRequest": {
            materialNo?: string;
            sourceWarehouseId?: string;
            destWarehouseId?: string;
            /** Format: double */
            quantity?: number;
            refNo?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.ChangeRoleRequest": {
            /** Format: int32 */
            roleId?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.CreateUserRequest": {
            name?: string;
            email?: string;
            password?: string;
            /** Format: int32 */
            roleId?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.RoleDto": {
            /** Format: int32 */
            roleId?: number;
            name?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UpdateUserRequest": {
            name?: string;
            email?: string;
            /** Format: int32 */
            roleId?: number;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.User.UserDto": {
            /** Format: int32 */
            userId?: number;
            name?: string;
            email?: string;
            /** Format: int32 */
            roleId?: number;
            roleName?: string;
            /** Format: date-time */
            createdAt?: string;
            isDeleted?: boolean;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.CreateWarehouseRequest": {
            code?: string;
            name?: string;
            location?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.UpdateWarehouseRequest": {
            name?: string;
            location?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.DTOs.Warehouse.WarehouseDto": {
            /** Format: int32 */
            warehouseId?: number;
            code?: string;
            name?: string;
            location?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpSettingsDto": {
            enabled?: boolean;
            host?: string;
            /** Format: int32 */
            port?: number;
            useSsl?: boolean;
            userName?: string;
            fromEmail?: string;
            fromName?: string;
            hasPassword?: boolean;
            provider?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestRequest": {
            to?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.Services.SmtpTestResultDto": {
            sent?: boolean;
            to?: string | null;
            message?: string;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.Services.UpdateNotificationPreferencesRequest": {
            emailEnabled?: boolean;
            alertEmail?: string | null;
            weeklyReportEnabled?: boolean;
            weeklyReportDay?: string | null;
        };
        "Stock_Warehouse_Tracking_Project_API.Application.Services.UpdateSmtpSettingsRequest": {
            enabled?: boolean;
            host?: string | null;
            /** Format: int32 */
            port?: number;
            useSsl?: boolean;
            userName?: string | null;
            fromEmail?: string | null;
            fromName?: string | null;
            password?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        "Stock_Warehouse_Tracking_Project_API.Domain.Enums.MovementType": 1 | 2 | 3;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
